// Code generated by mockery v1.0.0
package mocks

import image "github.com/jgimeno/go-imgrpc/image"
import mock "github.com/stretchr/testify/mock"

// Persistence is an autogenerated mock type for the Persistence type
type Persistence struct {
	mock.Mock
}

// GetById provides a mock function with given fields: id
func (_m *Persistence) GetById(id image.Id) *image.Image {
	ret := _m.Called(id)

	var r0 *image.Image
	if rf, ok := ret.Get(0).(func(image.Id) *image.Image); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.Image)
		}
	}

	return r0
}

// Save provides a mock function with given fields: _a0
func (_m *Persistence) Save(_a0 *image.Image) {
	_m.Called(_a0)
}
